# Generated by Django 4.2.2 on 2024-05-25 04:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electors', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0014_rename_display_name_group_codename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'منشور'), (2, 'خاص'), (3, 'في أنتظار الموافقة'), (4, 'يفتقد للبيانات'), (5, 'جاري العمل عليه'), (6, 'جديد'), (7, 'تجريبي'), (9, 'محذوف')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'عالي')], null=True)),
                ('moderators', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('campaigner_id', models.PositiveIntegerField()),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('instagram', models.CharField(blank=True, max_length=120, null=True)),
                ('website', models.CharField(blank=True, max_length=120, null=True)),
                ('campaign_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign',
                'db_table': 'campaign',
                'permissions': [('canViewCampaign', 'Can View Campaign'), ('canAddCampaign', 'Can Add Campaign'), ('canChangeCampaign', 'Can Change Campaign'), ('canDeleteCampaign', 'Can Delete Campaign'), ('canChangeCampaignModerator', 'can Change Campaign Moderator'), ('canChangeCampaignCandidate', 'can Change Campaign Candidate'), ('canChangeCampaignManager', 'can Change Campaign Manager'), ('canChangeCampaignAssistant', 'can Change Campaign Assistant')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CampaignGuaranteeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('member', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=8, null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Campaign Guarantee Group',
                'verbose_name_plural': 'المجاميع',
                'db_table': 'campaign_guarantee_group',
                'permissions': [('canViewCampaignGuaranteeGroup', 'Can View Campaign Guarantee Group'), ('canAddCampaignGuaranteeGroup', 'Can Add Campaign Guarantee Group'), ('canChangeCampaignGuaranteeGroup', 'Can Change Campaign Guarantee Group'), ('canDeleteCampaignGuaranteeGroup', 'Can Delete Campaign GuaranteeGroup')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='phone must be exactly 8 digits.', regex='^\\d{8}$')])),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'جديد'), (2, 'تم التواصل'), (3, 'تم التأكيد'), (4, 'غير مؤكد'), (5, 'غير معروف')], null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_members', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_role_members', to='auth.group')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_members', to='campaigns.campaignmember')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Member',
                'verbose_name_plural': 'Campaign Members',
                'db_table': 'campaign_member',
                'permissions': [('canViewCampaignMember', 'Can View Campaign Member'), ('canAddCampaignMember', 'Can Add Campaign Member'), ('canChangeCampaignMember', 'Can Change Campaign Member'), ('canDeleteCampaignMember', 'Can Delete Campaign Member')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CampaignGuarantee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign', models.IntegerField(blank=True, null=True)),
                ('member', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'جديد'), (2, 'تم التواصل'), (3, 'تم التأكيد'), (4, 'غير مؤكد'), (5, 'غير معروف')], null=True)),
                ('elector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_voter_guarantees', to='electors.elector')),
                ('guarantee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_elector_guarantee_groups', to='campaigns.campaignguaranteegroup')),
            ],
            options={
                'verbose_name': 'Campaign Guarantee',
                'verbose_name_plural': 'المضامين',
                'db_table': 'campaign_guarantee',
                'permissions': [('canViewCampaignGuarantee', 'Can View Campaign Guarantee'), ('canAddCampaignGuarantee', 'Can Add Campaign Guarantee'), ('canChangeCampaignGuarantee', 'Can Change Campaign Guarantee'), ('canDeleteCampaignGuarantee', 'Can Delete Campaign Guarantee')],
                'default_permissions': [],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type', 'campaigner_id'], name='campaign_campaig_b71203_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('campaign_type', 'campaigner_id')},
        ),
    ]
