# Generated by Django 5.0.4 on 2024-05-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='object_id',
            new_name='campaigner_id',
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('campaign_type', 'campaigner_id')},
        ),
    ]
