# Generated by Django 4.2.2 on 2024-06-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_rename_notes_electionparty_note_and_more'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaign_campaig_b71203_idx',
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campaign',
            name='election_candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elections.electioncandidate'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaigner_id',
        ),
    ]
