# Generated by Django 4.2.2 on 2023-11-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignsorting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsorting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='campaignsorting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaignsorting',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='campaignsorting',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='campaignsorting',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='campaignsorting',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='campaignsorting',
            name='updated_by',
        ),
    ]
