# Generated by Django 4.2.2 on 2023-10-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
    ]
