# Generated by Django 4.2.2 on 2023-11-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('campaigns', '0003_remove_campaignsorting_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignsorting',
            old_name='electionCandidate',
            new_name='election_candidate',
        ),
        migrations.RemoveField(
            model_name='campaignsorting',
            name='committee',
        ),
        migrations.AddField(
            model_name='campaignsorting',
            name='election_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_committee_sortees', to='elections.electioncommittee'),
        ),
    ]
