# Generated by Django 4.2.2 on 2024-05-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_election_candidate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type', 'campaigner_id'], name='campaign_campaig_b71203_idx'),
        ),
    ]
