# Generated by Django 4.2.2 on 2024-04-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '__first__'),
        ('campaigns', '0016_alter_campaignattendee_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignattendee',
            name='civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_attendees', to='voters.voter'),
        ),
        migrations.AlterField(
            model_name='campaignguarantee',
            name='civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_voter_guarantees', to='voters.voter'),
        ),
        migrations.AlterField(
            model_name='campaignpartyguarantee',
            name='civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_party_voter_guarantees', to='voters.voter'),
        ),
    ]
