# Generated by Django 4.2.2 on 2024-04-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0016_rename_electors_election_voters_and_more'),
        ('campaigns', '0020_campaignguaranteegroup_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignmember',
            options={'default_permissions': [], 'permissions': [('canViewCampaignMember', 'Can View Campaign Member'), ('canAddCampaignMember', 'Can Add Campaign Member'), ('canChangeCampaignMember', 'Can Change Campaign Member'), ('canDeleteCampaignMember', 'Can Delete Campaign Member')], 'verbose_name': 'Campaign Member', 'verbose_name_plural': 'Campaign Members'},
        ),
        migrations.CreateModel(
            name='campaignCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_campaigns', to='campaigns.campaign')),
                ('campaign_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_campaign_members', to='campaigns.campaignmember')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_committee_campaigns', to='elections.electioncommittee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Campaign Committee',
                'verbose_name_plural': 'Campaign Committees',
                'db_table': 'campaign_committee',
                'permissions': [('canViewCampaignCommittee', 'Can View Campaign Committee'), ('canAddCampaignCommittee', 'Can Add Campaign Committee'), ('canChangeCampaignCommittee', 'Can Change Campaign Committee'), ('canDeleteCampaignCommittees', 'Can Delete Campaign Committee')],
                'default_permissions': [],
            },
        ),
    ]
