# Generated by Django 4.2.2 on 2024-04-08 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0016_rename_electors_election_voters_and_more'),
        ('campaigns', '0021_alter_campaignmember_options_campaigncommittee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigncommittee',
            options={'default_permissions': [], 'permissions': [('canViewCampaignCommittee', 'Can View Campaign Committee'), ('canAddCampaignCommittee', 'Can Add Campaign Committee'), ('canChangeCampaignCommittee', 'Can Change Campaign Committee'), ('canDeleteCampaignCommittee', 'Can Delete Campaign Committee')], 'verbose_name': 'Campaign Committee', 'verbose_name_plural': 'Campaign Committees'},
        ),
        migrations.CreateModel(
            name='CampaignCommitteeSorter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_committee_sorter_campaigns', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_committee_sorter_committees', to='elections.electioncommittee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_committee_sorter_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Committee Sorter',
                'verbose_name_plural': 'Campaign Committee Sorters',
                'db_table': 'campaign_committee_sorter',
                'permissions': [('canViewCampaignCommitteeSorter', 'Can View Campaign Committee Sorter'), ('canAddCampaignCommitteeSorter', 'Can Add Campaign Committee Sorter'), ('canChangeCampaignCommitteeSorter', 'Can Change Campaign Committee Sorter'), ('canDeleteCampaignCommitteeSorter', 'Can Delete Campaign Committee Sorter')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CampaignCommitteeAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_committee_attendee_campaigns', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_committee_attendee_campaigns', to='elections.electioncommittee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_committee_attendee_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Committee Attendee',
                'verbose_name_plural': 'Campaign Committee Attendees',
                'db_table': 'campaign_committee_attendee',
                'permissions': [('canViewCampaignCommitteeAttendee', 'Can View Campaign Committee Attendee'), ('canAddCampaignCommitteeAttendee', 'Can Add Campaign Committee Attendee'), ('canChangeCampaignCommitteeAttendee', 'Can Change Campaign Committee Attendee'), ('canDeleteCampaignCommitteeAttendee', 'Can Delete Campaign Committee Attendee')],
                'default_permissions': [],
            },
        ),
    ]
