# Generated by Django 4.2.2 on 2024-04-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_rename_election_committee_campaigncommitteeattendee_committee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignguarantee',
            name='guarantee_group',
        ),
        migrations.AddField(
            model_name='campaignguarantee',
            name='guarantee_groups',
            field=models.ManyToManyField(blank=True, related_name='campaign_guarantees', to='campaigns.campaignguaranteegroup'),
        ),
    ]
