# Generated by Django 4.2.2 on 2023-11-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_electioncategory_alter_election_category_and_more'),
        ('categories', '0002_alter_area_created_by_alter_area_deleted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
