# Generated by Django 4.2.2 on 2023-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
