# Generated by Django 4.2.2 on 2023-07-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_elections_tags'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='elections',
        #     old_name='categories',
        #     new_name='category',
        # ),
        migrations.RenameField(
            model_name='elections',
            old_name='sub_categories',
            new_name='sub_category',
        ),
    ]
