// ElectionSchema Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Get ElectionSchemas
export const GET_ELECTION_SCHEMAS = "GET_ELECTION_SCHEMAS";

export const ADD_SCHEMA_TABLES = "ADD_SCHEMA_TABLES";

// Add ElectionSchema
export const ADD_ELECTION_SCHEMA = "ADD_ELECTION_SCHEMA";
export const ADD_ELECTION_SCHEMA_SUCCESS = "ADD_ELECTION_SCHEMA_SUCCESS";
export const ADD_ELECTION_SCHEMA_FAIL = "ADD_ELECTION_SCHEMA_FAIL";

// Edit ElectionSchema
export const UPDATE_ELECTION_SCHEMA = "UPDATE_ELECTION_SCHEMA";
export const UPDATE_ELECTION_SCHEMA_SUCCESS = "UPDATE_ELECTION_SCHEMA_SUCCESS";
export const UPDATE_ELECTION_SCHEMA_FAIL = "UPDATE_ELECTION_SCHEMA_FAIL";

// Delete ElectionSchema
export const DELETE_ELECTION_SCHEMA = "DELETE_ELECTION_SCHEMA";
export const DELETE_ELECTION_SCHEMA_SUCCESS = "DELETE_ELECTION_SCHEMA_SUCCESS";
export const DELETE_ELECTION_SCHEMA_FAIL = "DELETE_ELECTION_SCHEMA_FAIL";

// ElectionSchema Details
export const GET_ELECTION_SCHEMA_DETAILS = "GET_ELECTION_SCHEMA_DETAILS";

