// Committee Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

// Election Committees
export const GET_ELECTION_COMMITTEES = "GET_ELECTION_COMMITTEES";
export const GET_ELECTION_COMMITTEES_SUCCESS = "GET_ELECTION_COMMITTEES_SUCCESS";
export const GET_ELECTION_COMMITTEES_FAIL = "GET_ELECTION_COMMITTEES_FAIL";

// Add Election Committee
export const ADD_ELECTION_COMMITTEE = "ADD_ELECTION_COMMITTEE";
export const ADD_ELECTION_COMMITTEE_SUCCESS = "ADD_ELECTION_COMMITTEE_SUCCESS";
export const ADD_ELECTION_COMMITTEE_FAIL = "ADD_ELECTION_COMMITTEE_FAIL";

// Edit Election Committee
export const UPDATE_ELECTION_COMMITTEE = "UPDATE_ELECTION_COMMITTEE";
export const UPDATE_ELECTION_COMMITTEE_SUCCESS = "UPDATE_ELECTION_COMMITTEE_SUCCESS";
export const UPDATE_ELECTION_COMMITTEE_FAIL = "UPDATE_ELECTION_COMMITTEE_FAIL";

// Delete Election Committee
export const DELETE_ELECTION_COMMITTEE = "DELETE_ELECTION_COMMITTEE";
export const DELETE_ELECTION_COMMITTEE_SUCCESS = "DELETE_ELECTION_COMMITTEE_SUCCESS";
export const DELETE_ELECTION_COMMITTEE_FAIL = "DELETE_ELECTION_COMMITTEE_FAIL";

