# Generated by Django 4.2.2 on 2024-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('governorate', models.IntegerField(choices=[(1, 'الأحمدي'), (2, 'العاصمة'), (3, 'الفروانية'), (4, 'حولي'), (5, 'الجهراء'), (6, 'مبارك الكبير')])),
                ('tags', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'المنطقة',
                'verbose_name_plural': 'المناطق',
                'db_table': 'area',
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
