# Generated by Django 5.0.4 on 2024-04-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30)),
                ('governorate', models.IntegerField(choices=[(1, 'الأحمدي'), (2, 'العاصمة'), (3, 'الفروانية'), (4, 'حولي'), (5, 'الجهراء'), (6, 'مبارك الكبير')])),
            ],
        ),
    ]
