# Generated by Django 5.0.4 on 2024-04-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'default_permissions': [], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
    ]
