# Generated by Django 5.0.4 on 2024-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'default_permissions': [], 'managed': False, 'verbose_name': 'المنطقة', 'verbose_name_plural': 'المناطق'},
        ),
    ]
