# Generated by Django 5.0.4 on 2024-04-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_committee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
