# Generated by Django 4.2.2 on 2024-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_delete_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
