# Generated by Django 4.2.2 on 2024-05-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_area_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'default_permissions': [], 'managed': False, 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
