export const StatusOptions = [
  {
    id: 1,
    name: "Published",
    value: "Published",
    badgeClass: "badge bg-success",
    description: "Post is approved and viewable by everyone.",
    role: "Admin",
  },
  {
    id: 2,
    name: "Private",
    value: "Private",
    badgeClass: "badge bg-success",
    description: "Post viewable only by Admin role.",
    role: "Admin",
  },
  {
    id: 3,
    name: "Pending Approval",
    value: "Pending Approval",
    badgeClass: "badge bg-warning",
    description: "Post is complete and awaiting approval before publication.",
    role: "Moderator",
  },
  {
    id: 4,
    name: "Missing Data",
    value: "Missing Data",
    badgeClass: "badge bg-danger",
    description: "The post is incomplete and missing essential data.",
    role: "Moderator",
  },
  {
    id: 5,
    name: "Inprogress",
    value: "Inprogress",
    badgeClass: "badge bg-success",
    description: "Post is currently being worked on.",
    role: "Admin, Moderator",
  },
  {
    id: 6,
    name: "New",
    value: "New",
    badgeClass: "badge bg-success",
    description: "Newly created post awaiting further action.",
    role: "Admin, Moderator",
  },
  {
    id: 9,
    name: "Deleted",
    value: "Deleted",
    badgeClass: "badge bg-primary",
    description: "Post is in the trash and not viewable to the public.",
    role: "Admin, Moderator",
  },
];
