// ElectionStatistic Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Add Election
export const ADD_ELECTION_DATABASE = "ADD_ELECTION_DATABASE";
export const ADD_ELECTION_DATABASE_SUCCESS = "ADD_ELECTION_DATABASE_SUCCESS";
export const ADD_ELECTION_DATABASE_FAIL = "ADD_ELECTION_DATABASE_FAIL";



// Get ElectionStatistics
export const GET_ELECTION_STATISTICS = "GET_ELECTION_STATISTICS";
export const GET_ELECTORS_BY_FAMILY = "GET_ELECTORS_BY_FAMILY";

