# Generated by Django 4.2.2 on 2023-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elector",
            fields=[
                ("civil", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "family_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Undefined"), (1, "رجال"), (2, "نساء")],
                        null=True,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "membership_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("box_no", models.CharField(blank=True, max_length=255, null=True)),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Elector",
                "verbose_name_plural": "Elector",
                "db_table": "electors",
                "permissions": [
                    ("canViewElector", "Can View Elector"),
                    ("canAddElector", "Can Add Elector"),
                    ("canChangeElector", "Can Change Elector"),
                    ("canDeleteElector", "Can Delete Elector"),
                ],
                "default_permissions": [],
            },
        ),
    ]
