# Generated by Django 5.0.4 on 2024-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('second_name', models.TextField(blank=True, null=True)),
                ('third_name', models.TextField(blank=True, null=True)),
                ('fourth_name', models.TextField(blank=True, null=True)),
                ('fifth_name', models.TextField(blank=True, null=True)),
                ('sixth_name', models.TextField(blank=True, null=True)),
                ('seventh_name', models.TextField(blank=True, null=True)),
                ('eighth_name', models.TextField(blank=True, null=True)),
                ('ninth_name', models.TextField(blank=True, null=True)),
                ('tenth_name', models.TextField(blank=True, null=True)),
                ('eleventh_name', models.TextField(blank=True, null=True)),
                ('twelveth_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('sect', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area_name', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('lane', models.TextField(blank=True, null=True)),
                ('house', models.TextField(blank=True, null=True)),
                ('circle', models.TextField(blank=True, null=True)),
                ('committee_area', models.TextField(blank=True, null=True)),
                ('committee_name', models.TextField(blank=True, null=True)),
                ('letter', models.TextField(blank=True, null=True)),
                ('code_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Electors',
                'verbose_name_plural': 'Electorss',
                'db_table': 'electors',
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
