# Generated by Django 4.2.2 on 2024-04-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('second_name', models.TextField(blank=True, null=True)),
                ('third_name', models.TextField(blank=True, null=True)),
                ('fourth_name', models.TextField(blank=True, null=True)),
                ('fifth_name', models.TextField(blank=True, null=True)),
                ('sixth_name', models.TextField(blank=True, null=True)),
                ('seventh_name', models.TextField(blank=True, null=True)),
                ('eighth_name', models.TextField(blank=True, null=True)),
                ('ninth_name', models.TextField(blank=True, null=True)),
                ('tenth_name', models.TextField(blank=True, null=True)),
                ('eleventh_name', models.TextField(blank=True, null=True)),
                ('twelveth_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('tribe', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('sect', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True)),
                ('circle', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('lane', models.TextField(blank=True, null=True)),
                ('house', models.TextField(blank=True, null=True)),
                ('column6', models.TextField(blank=True, null=True)),
                ('national_table_name', models.TextField(blank=True, null=True)),
                ('status_code', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('committee', models.TextField(blank=True, null=True)),
                ('letter', models.TextField(blank=True, null=True)),
                ('code_char', models.TextField(blank=True, null=True)),
                ('vote', models.TextField(blank=True, null=True)),
                ('groups', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Electors',
                'verbose_name_plural': 'Electorss',
                'db_table': 'electors',
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
