# Generated by Django 5.0.4 on 2024-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elector',
            options={'default_permissions': [], 'managed': False, 'verbose_name': 'الناخب', 'verbose_name_plural': 'الناخبين'},
        ),
        migrations.AlterModelTable(
            name='elector',
            table='elector',
        ),
    ]
