# Generated by Django 4.2.2 on 2024-05-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0002_elector_delete_voter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elector',
        ),
    ]
