export const StatusOptions = [
  {
    id: 1,
    name: "منشور",
    value: "منشور",
    badgeClass: "badge bg-success",
    description: "تمت الموافقة على المنشور ويمكن للجميع مشاهدته.",
    role: "Admin",
  },
  {
    id: 2,
    name: "خاص",
    value: "خاص",
    badgeClass: "badge bg-success",
    description: "المنشور يمكن مشاهدته فقط بواسطة الإدارة.",
    role: "Admin",
  },
  {
    id: 3,
    name: "في أنتظار الموافقة ",
    value: "في أنتظار الموافقة",
    badgeClass: "badge bg-warning",
    description: "المنشور مكتمل وفي انتظار الموافقة قبل النشر.",
    role: "Moderator",
  },
  {
    id: 4,
    name: "يفتقد للبيانات",
    value: "يفتقد للبيانات",
    badgeClass: "badge bg-danger",
    description: "المنشور غير مكتمل ويفتقد لبيانات أساسية.",
    role: "Moderator",
  },
  {
    id: 5,
    name: "جاري العمل عليه",
    value: "جاري العمل عليه",
    badgeClass: "badge bg-success",
    description: "يتم العمل حاليًا على المنشور.",
    role: "Admin, Moderator",
  },
  {
    id: 6,
    name: "جديد",
    value: "جديد",
    badgeClass: "badge bg-success",
    description: "منشور جديد في انتظار مزيد من الإجراءات.",
    role: "Admin, Moderator",
  },
  {
    id: 9,
    name: "محذوف",
    value: "محذوف",
    badgeClass: "badge bg-primary",
    description: "المنشور في سلة المحذوفات ولا يمكن مشاهدته للعامة.",
    role: "Admin, Moderator",
  },
];
