# Generated by Django 4.2.2 on 2023-10-23 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'منشور'), (2, 'خاص'), (3, 'في أنتظار الموافقة'), (4, 'يفتقد للبيانات'), (5, 'جاري العمل عليه'), (6, 'جديد'), (9, 'محذوف')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(3, 'عالي'), (2, 'متوسط'), (1, 'منخفض')], null=True)),
                ('moderators', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'رجال'), (2, 'نساء')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidate',
                'permissions': [('canViewCandidate', 'Can View Candidate'), ('canAddCandidate', 'Can Add Candidate'), ('canChangeCandidate', 'Can Change Candidate'), ('canDeleteCandidate', 'Can Delete Candidate')],
                'default_permissions': [],
            },
        ),
    ]
