# Generated by Django 5.0.4 on 2024-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='denomination',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='family',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tribe',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
