# Generated by Django 5.0.4 on 2024-05-15 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_created_at_alter_party_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='party',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
    ]
