# Generated by Django 5.0.4 on 2024-05-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_rename_deleted_candidate_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'عالي')], null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'عالي')], null=True),
        ),
    ]
