# Generated by Django 5.0.4 on 2024-04-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('circle', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('voter_count', models.IntegerField(blank=True, null=True)),
                ('committee_count', models.IntegerField(blank=True, null=True)),
                ('total_voters', models.IntegerField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Election Committe',
                'verbose_name_plural': 'Election Committes',
                'db_table': 'election_committee',
                'permissions': [('canViewElectionCommittes', 'Can View Election Committes'), ('canAddElectionCommitte', 'Can Add Election Committe'), ('canChangeElectionCommitte', 'Can Change Election Committe'), ('canDeleteElectionCommitte', 'Can Delete Election Committe')],
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionCommitteeSubset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.TextField(blank=True, null=True)),
                ('letters', models.TextField(blank=True, null=True)),
                ('main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Election Committe Subset',
                'verbose_name_plural': 'Election Subsets',
                'db_table': 'election_committee_subset',
                'permissions': [('canViewElectionCommitteSubsets', 'Can View Election Committe Subsets'), ('canAddElectionCommitteSubset', 'Can Add Election Committe Subset'), ('canChangeElectionCommitteSubset', 'Can Change Election Committe Subset'), ('canDeleteElectionCommitteSubset', 'Can Delete Election Committe Subset')],
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionElector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('second_name', models.TextField(blank=True, null=True)),
                ('third_name', models.TextField(blank=True, null=True)),
                ('fourth_name', models.TextField(blank=True, null=True)),
                ('fifth_name', models.TextField(blank=True, null=True)),
                ('sixth_name', models.TextField(blank=True, null=True)),
                ('seventh_name', models.TextField(blank=True, null=True)),
                ('eighth_name', models.TextField(blank=True, null=True)),
                ('ninth_name', models.TextField(blank=True, null=True)),
                ('tenth_name', models.TextField(blank=True, null=True)),
                ('eleventh_name', models.TextField(blank=True, null=True)),
                ('twelveth_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('tribe', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('sect', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True)),
                ('circle', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('lane', models.TextField(blank=True, null=True)),
                ('house', models.TextField(blank=True, null=True)),
                ('column6', models.TextField(blank=True, null=True)),
                ('national_table_name', models.TextField(blank=True, null=True)),
                ('status_code', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('committee', models.TextField(blank=True, null=True)),
                ('letter', models.TextField(blank=True, null=True)),
                ('code_char', models.TextField(blank=True, null=True)),
                ('vote', models.TextField(blank=True, null=True)),
                ('groups', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Election Electors',
                'verbose_name_plural': 'Election Electorss',
                'db_table': 'election_electors',
                'permissions': [('canViewElectionElectors', 'Can View Election Electors'), ('canAddElectionElectors', 'Can Add Election Electors'), ('canChangeElectionElectors', 'Can Change Election Electors'), ('canDeleteElectionElectors', 'Can Delete Election Electors')],
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Elector',
        ),
        migrations.DeleteModel(
            name='SubCommittee',
        ),
    ]
