# Generated by Django 4.2.2 on 2024-04-07 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0017_alter_campaignattendee_civil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGuaranteeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_guarantee_group_members', to='campaigns.campaignmember')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Campaign Guarantee Group',
                'verbose_name_plural': 'Campaign Guarantee Groups',
                'db_table': 'campaign_guarantee_group',
                'permissions': [('canViewCampaignGuaranteeGroup', 'Can View Campaign Guarantee Group'), ('canAddCampaignGuaranteeGroup', 'Can Add Campaign Guarantee Group'), ('canChangeCampaignGuaranteeGroup', 'Can Change Campaign Guarantee Group'), ('canDeleteCampaignGuaranteeGroup', 'Can Delete Campaign GuaranteeGroup')],
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='campaignguarantee',
            name='guarantee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_guarantee_groups', to='campaigns.campaignguaranteegroup'),
        ),
    ]
