# Generated by Django 4.2.2 on 2024-04-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_campaignguaranteegroup_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignguaranteegroup',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
