# Generated by Django 4.2.2 on 2024-04-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_alter_campaigncommittee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigncommitteeattendee',
            old_name='election_committee',
            new_name='committee',
        ),
        migrations.RenameField(
            model_name='campaigncommitteesorter',
            old_name='election_committee',
            new_name='committee',
        ),
    ]
