# Generated by Django 4.2.2 on 2023-10-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidates",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="candidates/"),
        ),
    ]
