# Generated by Django 4.2.2 on 2023-10-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='twitter',
        ),
    ]
