# Generated by Django 4.2.2 on 2023-09-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='electors',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='electors',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='electors',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='electors',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='electors',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='electors',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='electors',
            name='updated_date',
        ),
    ]
