# Generated by Django 4.2.2 on 2023-07-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('election_id', models.CharField(max_length=255)),
                ('candidate_id', models.CharField(max_length=255)),
                ('results', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elections_candidates',
            },
        ),
        migrations.AlterModelTable(
            name='terms',
            table='Terms',
        ),
    ]
