# Generated by Django 4.2.2 on 2023-10-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="website",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
