# Generated by Django 4.2.2 on 2023-10-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'default_permissions': [], 'permissions': [('canViewCampaign', 'Can View Campaign'), ('canAddCampaign', 'Can Add Campaign'), ('canChangeCampaign', 'Can Change Campaign'), ('canDeleteCampaign', 'Can Delete Campaign'), ('canChangeCampaignModerator', 'can Change Campaign Moderator'), ('canChangeCampaignCandidate', 'can Change Campaign Candidate'), ('canChangeCampaignManager', 'can Change Campaign Manager'), ('canChangeCampaignAssistant', 'can Change Campaign Assistant')], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaign'},
        ),
    ]
