# Generated by Django 4.2.2 on 2023-10-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_electioncommittees_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electioncommittees',
            name='name2',
        ),
    ]
