# Generated by Django 4.2.2 on 2023-10-04 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0002_alter_candidates_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="areas",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="campaignguarantees",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="campaignmembers",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="campaigns",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="candidates",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="categories",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="electionattendees",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="electioncandidates",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="electioncommitteeresults",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="electioncommittees",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="elections",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
    ]
