# Generated by Django 4.2.2 on 2023-10-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_campaign_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='first_winner_votes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='last_winner_votes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
