# Generated by Django 4.2.2 on 2023-10-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_remove_areas_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='events',
            new_name='target_votes',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='results',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='target_score',
        ),
    ]
