# Generated by Django 4.2.2 on 2023-10-04 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0003_remove_areas_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigns",
            name="title",
        ),
    ]
