# Generated by Django 4.2.2 on 2023-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0003_user_created_by_user_created_date_user_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, null=True, unique=True)),
                ("value", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configuration",
                "db_table": "config",
            },
        ),
    ]
