# Generated by Django 4.2.3 on 2023-07-21 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0005_remove_electioncandidates_results"),
    ]

    operations = [
        migrations.RenameField(
            model_name="electioncandidates",
            old_name="votes_received",
            new_name="votes",
        ),
    ]
