# Generated by Django 4.2.2 on 2023-09-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0005_rename_created_date_areas_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="areas",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="candidates",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="categories",
            old_name="description",
            new_name="desc",
        ),
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
        migrations.AddField(
            model_name="user",
            name="desc",
            field=models.TextField(blank=True, verbose_name="desc"),
        ),
    ]
