# Generated by Django 4.2.3 on 2023-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0006_rename_votes_received_electioncandidates_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terms",
            name="sub_group",
        ),
        migrations.AddField(
            model_name="terms",
            name="parent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="terms",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="terms",
            name="group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="terms",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="terms",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
