# Generated by Django 4.2.2 on 2023-10-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_rename_desc_areas_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='election_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_campaigns', to='restapi.electioncandidates'),
        ),
    ]
