# Generated by Django 4.2.2 on 2023-07-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_remove_terms_sub_group_terms_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='group',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='terms',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='del_flag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.terms'),
        ),
    ]
