# Generated by Django 4.2.2 on 2023-10-06 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0007_alter_campaignattendees_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignattendees",
            options={
                "verbose_name": "Campaign Attendee",
                "verbose_name_plural": "Campaign Attendees",
            },
        ),
        migrations.AlterField(
            model_name="campaignattendees",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendant_elections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
