# Generated by Django 4.2.2 on 2023-10-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("restapi", "0008_alter_campaignattendees_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignmembers",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_members_by_rank",
                to="auth.group",
            ),
        ),
    ]
