# Generated by Django 4.2.2 on 2023-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_campaigns_election_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncandidates',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
