# Generated by Django 4.2.3 on 2023-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0009_categories_delete_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaigns",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("election_candidate_id", models.CharField(max_length=255)),
                ("campaign_name", models.CharField(max_length=255)),
                ("campaign_description", models.TextField(blank=True, null=True)),
                ("campaign_start_date", models.DateTimeField(blank=True, null=True)),
                ("campaign_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "campaign_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "campaign_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaign_images/"
                    ),
                ),
                (
                    "campaign_video",
                    models.FileField(
                        blank=True, null=True, upload_to="campaign_videos/"
                    ),
                ),
                (
                    "social_media_handles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("campaign_website", models.URLField(blank=True, null=True)),
                ("outreach_events", models.PositiveIntegerField(blank=True, null=True)),
                ("attendees", models.PositiveIntegerField(blank=True, null=True)),
                ("media_coverage", models.PositiveIntegerField(blank=True, null=True)),
                ("campaign_results", models.TextField(blank=True, null=True)),
                ("del_flag", models.IntegerField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("del_flag", models.IntegerField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Tags",
            },
        ),
    ]
