# Generated by Django 4.2.2 on 2023-10-06 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0009_alter_campaignmembers_rank"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
    ]
