# Generated by Django 4.2.3 on 2023-07-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0010_campaigns_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electioncandidates",
            name="candidate_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="election_candidates",
                to="restapi.candidates",
            ),
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="election_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restapi.elections"
            ),
        ),
    ]
