# Generated by Django 4.2.2 on 2023-10-06 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0011_alter_user_instagram_alter_user_twitter_userprofile"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="auth_user_profile",
        ),
    ]
