# Generated by Django 4.2.2 on 2023-10-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0012_alter_electioncandidates_candidate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elections",
            old_name="result",
            new_name="elect_result",
        ),
        migrations.RenameField(
            model_name="elections",
            old_name="seats",
            new_name="elect_seats",
        ),
        migrations.RenameField(
            model_name="elections",
            old_name="type",
            new_name="elect_type",
        ),
        migrations.RenameField(
            model_name="elections",
            old_name="votes",
            new_name="elect_votes",
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="election_candidates",
                to="restapi.candidates",
            ),
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="election",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_elections",
                to="restapi.elections",
            ),
        ),
    ]
