# Generated by Django 4.2.2 on 2023-10-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_alter_electioncandidates_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electioncandidates',
            options={'permissions': [('add_election_candidates', 'Can add election candidates')], 'verbose_name': 'Election Candidate', 'verbose_name_plural': 'Election Candidates'},
        ),
    ]
