# Generated by Django 4.2.3 on 2023-07-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0013_remove_electioncandidates_candidate_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigns",
            name="election_candidate_id",
        ),
        migrations.AddField(
            model_name="campaigns",
            name="election_candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="restapi.electioncandidates",
            ),
        ),
    ]
