# Generated by Django 4.2.2 on 2023-10-08 09:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_alter_electioncandidates_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Test Now',
                'verbose_name_plural': 'Test Nows',
                'db_table': 'test_now',
                'default_permissions': [],
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
