# Generated by Django 4.2.2 on 2023-10-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_delete_projectinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elections',
            old_name='duedate',
            new_name='due_date',
        ),
    ]
