# Generated by Django 4.2.3 on 2023-07-26 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0014_remove_campaigns_election_candidate_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaigns",
            old_name="campaign_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="outreach_events",
            new_name="events",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="campaign_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="campaign_results",
            new_name="results",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="campaign_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="campaign_name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="campaign_video",
            new_name="video",
        ),
        migrations.RenameField(
            model_name="campaigns",
            old_name="campaign_website",
            new_name="website",
        ),
        migrations.RemoveField(
            model_name="campaigns",
            name="campaign_budget",
        ),
        migrations.RemoveField(
            model_name="campaigns",
            name="campaign_end_date",
        ),
        migrations.RemoveField(
            model_name="campaigns",
            name="campaign_start_date",
        ),
    ]
