# Generated by Django 4.2.2 on 2023-10-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0014_delete_authgroupcategory_remove_userprofile_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "auth_group_category",
            },
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
    ]
