# Generated by Django 4.2.2 on 2023-10-02 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0014_delete_projectinfo_rename_duedate_elections_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electioncandidates",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="electioncandidates",
            name="moderators",
        ),
        migrations.RemoveField(
            model_name="electioncandidates",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="electioncandidates",
            name="status",
        ),
    ]
