# Generated by Django 4.2.2 on 2023-10-07 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0015_authcategory_alter_user_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthCategory",
        ),
    ]
