# Generated by Django 4.2.3 on 2023-07-27 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0015_rename_campaign_description_campaigns_description_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="electioncandidates",
            table="election_candidates",
        ),
    ]
