# Generated by Django 4.2.2 on 2023-07-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_alter_electioncandidates_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='moderators',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='electioncandidates',
            table='election_candidate',
        ),
    ]
