# Generated by Django 4.2.2 on 2023-10-13 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0016_alter_areas_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignmembers",
            old_name="rank",
            new_name="role",
        ),
    ]
