# Generated by Django 4.2.3 on 2023-07-28 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0017_candidates_moderators_alter_electioncandidates_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="campaigns",
            table="Campaign",
        ),
        migrations.AlterModelTable(
            name="candidates",
            table="candidate",
        ),
        migrations.AlterModelTable(
            name="elections",
            table="election",
        ),
    ]
