# Generated by Django 4.2.2 on 2023-10-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0021_rename_display_name_group_role"),
        ("restapi", "0017_rename_rank_campaignmembers_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignmembers",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_members_by_role",
                to="auth.group",
            ),
        ),
    ]
