# Generated by Django 4.2.2 on 2023-10-14 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0018_alter_campaignmembers_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignattendees",
            old_name="elector",
            new_name="civil",
        ),
    ]
