# Generated by Django 4.2.3 on 2023-07-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0018_alter_campaigns_table_alter_candidates_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigns",
            name="image",
        ),
        migrations.AddField(
            model_name="campaigns",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns/"),
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="campaign/videos/"),
        ),
    ]
