# Generated by Django 4.2.3 on 2023-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0019_remove_campaigns_image_campaigns_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigns",
            name="banner",
            field=models.FileField(default="default.jpg", upload_to="campaigns/"),
        ),
    ]
