# Generated by Django 4.2.2 on 2023-10-14 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0021_rename_display_name_group_role"),
        ("restapi", "0019_rename_elector_campaignattendees_civil"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Areas",
            new_name="Area",
        ),
        migrations.RenameModel(
            old_name="Campaigns",
            new_name="Campaign",
        ),
        migrations.RenameModel(
            old_name="CampaignAttendees",
            new_name="CampaignAttendee",
        ),
        migrations.RenameModel(
            old_name="CampaignGuarantees",
            new_name="CampaignGuarantee",
        ),
        migrations.RenameModel(
            old_name="CampaignMembers",
            new_name="CampaignMember",
        ),
        migrations.RenameModel(
            old_name="Candidates",
            new_name="Candidate",
        ),
        migrations.RenameModel(
            old_name="Categories",
            new_name="Categorie",
        ),
        migrations.RenameModel(
            old_name="Configs",
            new_name="Config",
        ),
        migrations.RenameModel(
            old_name="Elections",
            new_name="Election",
        ),
        migrations.RenameModel(
            old_name="ElectionCandidates",
            new_name="ElectionCandidate",
        ),
        migrations.RenameModel(
            old_name="ElectionCommittees",
            new_name="ElectionCommittee",
        ),
        migrations.RenameModel(
            old_name="ElectionCommitteeResults",
            new_name="ElectionCommitteeResult",
        ),
        migrations.RenameModel(
            old_name="Electors",
            new_name="Elector",
        ),
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "Area", "verbose_name_plural": "Area"},
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={"verbose_name": "Campaign", "verbose_name_plural": "Campaign"},
        ),
        migrations.AlterModelOptions(
            name="candidate",
            options={"verbose_name": "Candidate", "verbose_name_plural": "Candidate"},
        ),
        migrations.AlterModelOptions(
            name="categorie",
            options={"verbose_name": "Category", "verbose_name_plural": "Categorie"},
        ),
        migrations.AlterModelOptions(
            name="election",
            options={"verbose_name": "Election", "verbose_name_plural": "Election"},
        ),
        migrations.AlterModelOptions(
            name="electioncandidate",
            options={
                "permissions": [
                    ("add_election_candidates", "Can add election candidates")
                ],
                "verbose_name": "Election Candidate",
                "verbose_name_plural": "Election Candidate",
            },
        ),
        migrations.AlterModelOptions(
            name="elector",
            options={"verbose_name": "Elector", "verbose_name_plural": "Elector"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tag"},
        ),
        migrations.AlterModelTable(
            name="tag",
            table="Tag",
        ),
    ]
