# Generated by Django 4.2.2 on 2023-10-14 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0020_rename_areas_area_rename_campaigns_campaign_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categorie",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Category"},
        ),
    ]
