# Generated by Django 4.2.3 on 2023-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0020_alter_campaigns_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigns",
            name="video",
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="banner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
