# Generated by Django 4.2.2 on 2023-10-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0021_rename_display_name_group_role"),
        ("restapi", "0021_rename_categorie_category_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignattendee",
            name="election",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="election_attendees",
                to="restapi.election",
            ),
        ),
        migrations.AlterField(
            model_name="campaignattendee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendant_attendees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaignguarantee",
            name="civil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elector_guarantees",
                to="restapi.elector",
            ),
        ),
        migrations.AlterField(
            model_name="campaignguarantee",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guarantee_guarantors",
                to="restapi.campaignmember",
            ),
        ),
        migrations.AlterField(
            model_name="campaignmember",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_role_members",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="campaignmember",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_members",
                to="restapi.campaignmember",
            ),
        ),
        migrations.AlterField(
            model_name="campaignmember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="campaignattendee",
            table="campaign_attendee",
        ),
    ]
