# Generated by Django 4.2.3 on 2023-07-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0021_remove_campaigns_video_alter_campaigns_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigns",
            name="election_candidate",
        ),
        migrations.AddField(
            model_name="electioncandidates",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapi.campaigns",
            ),
        ),
    ]
