# Generated by Django 4.2.3 on 2023-07-28 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0022_remove_campaigns_election_candidate_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ElectionCandidates",
            new_name="Participants",
        ),
        migrations.AlterModelTable(
            name="participants",
            table="participant",
        ),
    ]
