# Generated by Django 4.2.3 on 2023-07-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0023_rename_electioncandidates_participants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Electioncandidates",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("votes", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("is_winner", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("del_flag", models.IntegerField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="restapi.campaigns",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="restapi.candidates",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="restapi.elections",
                    ),
                ),
            ],
            options={
                "db_table": "election_candidate",
            },
        ),
        migrations.DeleteModel(
            name="Participants",
        ),
    ]
