# Generated by Django 4.2.2 on 2023-07-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restapi", "0024_electioncandidates_delete_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elections",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="created_elections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="elections",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="updated_elections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="elections",
            name="updated_date",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
