# Generated by Django 4.2.3 on 2023-07-29 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0025_alter_elections_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elections",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 29, 13, 6, 33, 652438, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="elections",
            name="updated_date",
            field=models.IntegerField(verbose_name=models.DateTimeField(auto_now=True)),
        ),
    ]
