# Generated by Django 4.2.3 on 2023-07-29 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0026_alter_elections_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elections",
            name="created_date",
            field=models.IntegerField(
                default=django.utils.timezone.now,
                verbose_name=models.DateTimeField(auto_now_add=True),
            ),
        ),
        migrations.AlterField(
            model_name="elections",
            name="updated_date",
            field=models.IntegerField(
                default=django.utils.timezone.now,
                verbose_name=models.DateTimeField(auto_now=True),
            ),
        ),
    ]
