# Generated by Django 4.2.3 on 2023-07-29 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0027_alter_elections_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elections",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="elections",
            name="updated_date",
        ),
    ]
