# Generated by Django 4.2.3 on 2023-07-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0028_remove_elections_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elections",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-07-31T14:12:02.074396+00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="elections",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
