# Generated by Django 4.2.3 on 2023-07-31 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restapi", "0029_elections_created_date_elections_updated_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tags",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tags",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="tags",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="tags",
            name="updated_date",
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="created_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-07-31T14:18:52.043164+00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="del_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="updated_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, default="2023-07-31T14:18:58.315793+00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidates",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="created_candidates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidates",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-07-31T14:19:00.705105+00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidates",
            name="del_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="candidates",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="updated_candidates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidates",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, default="2023-07-31T14:19:02.437365+00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categories",
            name="del_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="created_electionCandidates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-07-31T14:19:04.246882+00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="del_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="updated_electionCandidates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="electioncandidates",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, default="2023-07-31T14:19:06.420636+00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="elections",
            name="del_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="del_flag",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
