# Generated by Django 4.2.3 on 2023-08-03 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0031_elections_election_type_elections_result_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elections",
            name="candidates",
        ),
    ]
