# Generated by Django 4.2.3 on 2023-08-03 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0033_rename_election_type_elections_result_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaigns",
            old_name="del_flag",
            new_name="deleted",
        ),
        migrations.RenameField(
            model_name="candidates",
            old_name="del_flag",
            new_name="deleted",
        ),
        migrations.RenameField(
            model_name="categories",
            old_name="del_flag",
            new_name="deleted",
        ),
        migrations.RenameField(
            model_name="electioncandidates",
            old_name="del_flag",
            new_name="deleted",
        ),
        migrations.RenameField(
            model_name="elections",
            old_name="del_flag",
            new_name="deleted",
        ),
        migrations.RenameField(
            model_name="tags",
            old_name="del_flag",
            new_name="deleted",
        ),
    ]
