# Generated by Django 4.2.3 on 2023-08-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0034_rename_del_flag_campaigns_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="Category",
        ),
        migrations.CreateModel(
            name="Areas",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restapi.areas",
                    ),
                ),
            ],
            options={
                "db_table": "area",
            },
        ),
    ]
