# Generated by Django 4.2.2 on 2023-08-05 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0035_alter_categories_table_areas"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
