# Generated by Django 4.2.2 on 2023-08-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0036_alter_categories_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='elections_category', to='restapi.categories'),
        ),
    ]
