# Generated by Django 4.2.2 on 2023-08-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0037_alter_elections_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elections',
            name='sub_category',
        ),
    ]
