# Generated by Django 4.2.2 on 2023-08-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0039_elections_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electioncandidates",
            name="campaign",
        ),
        migrations.AddField(
            model_name="campaigns",
            name="election_candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="restapi.electioncandidates",
            ),
        ),
    ]
