# Generated by Django 4.2.2 on 2023-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0040_remove_electioncandidates_campaign_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigns",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns/"),
        ),
    ]
