# Generated by Django 4.2.2 on 2023-08-09 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0041_alter_campaigns_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areas',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidates',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categories',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='electioncandidates',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_election_candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electioncandidates',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='elections',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_election', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elections',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areas',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areas',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areas',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_banners/'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_campaign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_campaign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electioncandidates',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_election_candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioncandidates',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_election_candidate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elections',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_election', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elections',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_election', to=settings.AUTH_USER_MODEL),
        ),
    ]
