# Generated by Django 4.2.2 on 2023-08-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0042_areas_deleted_by_areas_deleted_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaigns',
            table='campaign',
        ),
    ]
