# Generated by Django 4.2.2 on 2023-08-09 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0043_alter_campaigns_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='moderators',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='electioncandidates',
            name='moderators',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electioncandidates',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areas',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areas',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioncandidates',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_election_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioncandidates',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_election_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioncandidates',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electioncandidates',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_election_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elections',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elections',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elections',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elections',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='elections',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tags',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tags',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampaignTeams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='restapi.campaigns')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_campaign_teams', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_campaign_teams', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_campaign_teams', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_team',
            },
        ),
    ]
