# Generated by Django 4.2.2 on 2023-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0045_campaignmembers_delete_campaignteams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='moderators',
        ),
    ]
