# Generated by Django 4.2.2 on 2023-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0046_remove_campaigns_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='moderators',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
