# Generated by Django 4.2.2 on 2023-08-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0047_campaigns_moderators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='elections',
            old_name='title',
            new_name='name',
        ),
    ]
