# Generated by Django 4.2.3 on 2023-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0048_rename_title_campaigns_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidates",
            name="gender",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
