# Generated by Django 4.2.2 on 2023-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0051_elections_attendees_elections_electors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaigns",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="campaigns",
            name="image",
        ),
        migrations.AlterField(
            model_name="campaigns",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns/"),
        ),
    ]
