# Generated by Django 4.2.2 on 2023-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0052_rename_name_campaigns_title_remove_campaigns_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidates",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=""
            ),
        ),
    ]
