# Generated by Django 4.2.2 on 2023-08-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0057_remove_candidates_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
