# Generated by Django 4.2.3 on 2023-08-15 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0058_candidates_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="electioncandidates",
            old_name="remarks",
            new_name="notes",
        ),
    ]
