# Generated by Django 4.2.2 on 2023-08-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0059_rename_remarks_electioncandidates_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmembers',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electioncandidates',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elections',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
