# Generated by Django 4.2.2 on 2023-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0063_remove_elections_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
