# Generated by Django 4.2.2 on 2023-08-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0064_elections_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignmembers",
            name="commiittee",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignmembers",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_members",
                to="restapi.campaignmembers",
            ),
        ),
    ]
