# Generated by Django 4.2.2 on 2023-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0066_electioncommittees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Electors",
            fields=[
                ("civil", models.BigAutoField(primary_key=True, serialize=False)),
                ("name_1", models.CharField(blank=True, max_length=255, null=True)),
                ("name_2", models.CharField(blank=True, max_length=255, null=True)),
                ("name_3", models.CharField(blank=True, max_length=255, null=True)),
                ("name_4", models.CharField(blank=True, max_length=255, null=True)),
                ("name_5", models.CharField(blank=True, max_length=255, null=True)),
                ("name_6", models.CharField(blank=True, max_length=255, null=True)),
                ("name_7", models.CharField(blank=True, max_length=255, null=True)),
                ("name_8", models.CharField(blank=True, max_length=255, null=True)),
                ("name_9", models.CharField(blank=True, max_length=255, null=True)),
                ("name_10", models.CharField(blank=True, max_length=255, null=True)),
                ("last_1", models.CharField(blank=True, max_length=255, null=True)),
                ("last_2", models.CharField(blank=True, max_length=255, null=True)),
                ("last_3", models.CharField(blank=True, max_length=255, null=True)),
                ("last_4", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.IntegerField(blank=True, null=True)),
                ("member_no", models.CharField(blank=True, max_length=255, null=True)),
                ("box_no", models.CharField(blank=True, max_length=255, null=True)),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "elector",
            },
        ),
    ]
