# Generated by Django 4.2.2 on 2023-08-17 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restapi", "0067_electors"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Guarantees",
            new_name="CampaignGuarantees",
        ),
        migrations.AlterModelTable(
            name="campaignguarantees",
            table="campaign_guarantee",
        ),
    ]
