# Generated by Django 4.2.2 on 2023-08-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0068_rename_guarantees_campaignguarantees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignguarantees",
            name="civil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_guarantees",
                to="restapi.electors",
            ),
        ),
        migrations.AlterModelTable(
            name="electors",
            table=None,
        ),
    ]
