# Generated by Django 4.2.2 on 2023-08-18 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "restapi",
            "0069_alter_campaignguarantees_civil_alter_attendees_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attendees",
            table="attendee",
        ),
        # migrations.AlterModelTable(
        #     name="electors",
        #     table="elector",
        # ),
    ]
