# Generated by Django 4.2.2 on 2023-08-18 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0070_alter_attendees_table_alter_electors_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendees",
        ),
    ]
