# Generated by Django 4.2.2 on 2023-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0072_attendees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignguarantees",
            name="civil",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
