# Generated by Django 4.2.2 on 2023-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0075_electionattendees_delete_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignguarantees',
            name='mobile',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
