# Generated by Django 4.2.2 on 2023-08-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0076_campaignguarantees_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionattendees',
            old_name='civil',
            new_name='elector',
        ),
    ]
