# Generated by Django 4.2.3 on 2023-08-23 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0077_rename_civil_electionattendees_elector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignmembers",
            name="role",
        ),
        migrations.AddField(
            model_name="campaignmembers",
            name="civil",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Civil must be exactly 12 digits.", regex="^\\d{12}$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="campaignmembers",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile must be exactly 8 digits.", regex="^\\d{8}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="campaignmembers",
            name="commiittee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="restapi.electioncommittees",
            ),
        ),
    ]
