# Generated by Django 4.2.3 on 2023-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0079_rename_commiittee_campaignmembers_committee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elections",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
