# Generated by Django 4.2.3 on 2023-08-24 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0080_elections_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elections",
            name="committees",
        ),
        migrations.AlterModelTable(
            name="electioncommittees",
            table="election_committee",
        ),
    ]
