# Generated by Django 4.2.2 on 2023-08-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0081_remove_elections_committees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignguarantees',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_campaigns', to='restapi.campaigns'),
        ),
    ]
