# Generated by Django 4.2.2 on 2023-08-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0082_campaignguarantees_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignguarantees',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaignguarantees',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='campaignguarantees',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='campaignguarantees',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='campaignguarantees',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='campaignguarantees',
            name='updated_date',
        ),
        migrations.AlterModelTable(
            name='electionattendees',
            table='election_attendee',
        ),
    ]
