# Generated by Django 4.2.2 on 2023-08-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0083_remove_campaignguarantees_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignguarantees',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_guarantee_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignguarantees',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignguarantees',
            name='deleted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_guarantee_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignguarantees',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaignguarantees',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_guarantee_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignguarantees',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
