# Generated by Django 4.2.2 on 2023-08-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0084_campaignguarantees_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionattendees",
            name="committee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendee_election_committees",
                to="restapi.electioncommittees",
            ),
        ),
    ]
