# Generated by Django 4.2.2 on 2023-09-11 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "restapi",
            "0087_alter_elections_created_date_alter_elections_deleted_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="electors",
            old_name="last_1",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="last_2",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="last_3",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="last_4",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_1",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_10",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_2",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_3",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_4",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_5",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_6",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_7",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_8",
        ),
        migrations.RemoveField(
            model_name="electors",
            name="name_9",
        ),
    ]
