# Generated by Django 4.2.2 on 2023-09-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0088_rename_last_1_electors_full_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="electors",
            old_name="member_no",
            new_name="family_name",
        ),
        migrations.AddField(
            model_name="electors",
            name="membership_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="electors",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
