# Generated by Django 4.2.2 on 2023-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0089_rename_member_no_electors_family_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigns',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='candidates',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='electioncandidates',
            options={'verbose_name': 'Election Candidate', 'verbose_name_plural': 'Election Candidates'},
        ),
        migrations.AlterModelOptions(
            name='electioncommittees',
            options={'verbose_name': 'Election Committe', 'verbose_name_plural': 'Election Committes'},
        ),
        migrations.AlterModelOptions(
            name='elections',
            options={'verbose_name': 'Election', 'verbose_name_plural': 'Elections'},
        ),
        migrations.RenameField(
            model_name='campaigns',
            old_name='social_media_handles',
            new_name='instagram',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
