# Generated by Django 4.2.2 on 2023-09-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0092_alter_campaigns_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='campaignguarantees',
            options={'verbose_name': 'Campaign Guarantee', 'verbose_name_plural': 'Campaign Guarantees'},
        ),
        migrations.AlterModelOptions(
            name='campaignmembers',
            options={'verbose_name': 'Campaign Member', 'verbose_name_plural': 'Campaign Members'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='electionattendees',
            options={'verbose_name': 'Election Attendee', 'verbose_name_plural': 'Election Attendees'},
        ),
        migrations.AlterModelOptions(
            name='electors',
            options={'verbose_name': 'Elector', 'verbose_name_plural': 'Electors'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='campaignguarantees',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Contacted'), (3, 'Confirmed'), (4, 'Not Confirmed')], default=1),
        ),
        migrations.AlterField(
            model_name='campaignmembers',
            name='rank',
            field=models.CharField(blank=True, choices=[('1', 'Party'), ('2', 'Candidate'), ('3', 'Supervisor'), ('4', 'Guarantor'), ('5', 'Attendant'), ('6', 'Sorter'), ('10', 'Moderator')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='electors',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
