# Generated by Django 4.2.2 on 2023-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0094_auto_20230915_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncommittees',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='campaignmembers',
            name='rank',
            field=models.IntegerField(blank=True, choices=[('1', 'Party'), ('2', 'Candidate'), ('3', 'Supervisor'), ('4', 'Guarantor'), ('5', 'Attendant'), ('6', 'Sorter'), ('10', 'Moderator')], null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='electors',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
