# Generated by Django 4.2.2 on 2023-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0098_rename_committeeresults_electioncommitteeresults_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elections",
            name="electors_females",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="elections",
            name="electors_males",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="elections",
            name="attendees",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="elections",
            name="electors",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="elections",
            name="result",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="elections",
            name="seats",
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="elections",
            name="type",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="elections",
            name="votes",
            field=models.IntegerField(blank=True, max_length=7, null=True),
        ),
    ]
