# Generated by Django 4.2.2 on 2023-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "restapi",
            "0099_elections_electors_females_elections_electors_males_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="elections",
            name="attendees_females",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="elections",
            name="attendees_males",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
