# Generated by Django 4.2.2 on 2023-09-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0100_elections_attendees_females_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='attendees',
            new_name='target_score',
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='elections/'),
        ),
        migrations.AlterField(
            model_name='elections',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elections',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
