# Generated by Django 4.2.2 on 2023-09-21 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0101_rename_attendees_campaigns_target_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigns",
            name="target_score",
        ),
    ]
