# Generated by Django 4.2.2 on 2023-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0102_remove_campaigns_target_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigns",
            name="target_score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
