# Generated by Django 4.2.2 on 2023-09-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0103_campaigns_target_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elections',
            name='description',
        ),
        migrations.RemoveField(
            model_name='elections',
            name='image',
        ),
        migrations.RemoveField(
            model_name='elections',
            name='name',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'رجال'), (2, 'نساء')], default=0),
        ),
        migrations.AlterField(
            model_name='electioncommittees',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'رجال'), (2, 'نساء')], default=0),
        ),
        migrations.AlterField(
            model_name='elections',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_elections', to='restapi.categories'),
        ),
        migrations.AlterField(
            model_name='elections',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elections',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_elections', to='restapi.categories'),
        ),
        migrations.AlterField(
            model_name='elections',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_elections', to='restapi.categories'),
        ),
        migrations.AlterField(
            model_name='elections',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electors',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'رجال'), (2, 'نساء')], default=0),
        ),
    ]
