# Generated by Django 4.2.2 on 2023-09-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0104_remove_elections_description_remove_elections_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elections',
            name='tags',
        ),
    ]
