// ElectionStatistic Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Add Election
export const GET_ELECTORS = "GET_ELECTORS";
export const ADD_ELECTOR = "ADD_ELECTOR";
export const ADD_ELECTOR_SUCCESS = "ADD_ELECTOR_SUCCESS";
export const ADD_ELECTOR_FAIL = "ADD_ELECTOR_FAIL";



// Get ElectionStatistics
export const GET_ELECTORS_BY_ALL = "GET_ELECTORS_BY_ALL";
export const GET_ELECTORS_BY_CATEGORY = "GET_ELECTORS_BY_CATEGORY";


// electorsBySearch
export const GET_ELECTORS_BY_SEARCH = "GET_ELECTORS_BY_SEARCH";
export const GET_ELECTOR_RELATED_ELECTORS = "GET_ELECTOR_RELATED_ELECTORS";


