<<<<<<< HEAD
// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_ALL_ELECTORS = "GET_ALL_ELECTORS";
export const GET_ELECTORS = "GET_ELECTORS";

// Add Elector
export const ADD_NEW_ELECTOR = "ADD_NEW_ELECTOR";
export const ADD_ELECTOR_SUCCESS = "ADD_ELECTOR_SUCCESS";
export const ADD_ELECTOR_FAIL = "ADD_ELECTOR_FAIL";

// Edit Elector
export const UPDATE_ELECTOR = "UPDATE_ELECTOR";
export const UPDATE_ELECTOR_SUCCESS = "UPDATE_ELECTOR_SUCCESS";
export const UPDATE_ELECTOR_FAIL = "UPDATE_ELECTOR_FAIL";

// Delete Elector
export const DELETE_ELECTOR = "DELETE_ELECTOR";
export const DELETE_ELECTOR_SUCCESS = "DELETE_ELECTOR_SUCCESS";
export const DELETE_ELECTOR_FAIL = "DELETE_ELECTOR_FAIL";
=======
// ElectionStatistic Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Add Election
export const GET_ELECTORS = "GET_ELECTORS";
export const ADD_ELECTOR = "ADD_ELECTOR";
export const ADD_ELECTOR_SUCCESS = "ADD_ELECTOR_SUCCESS";
export const ADD_ELECTOR_FAIL = "ADD_ELECTOR_FAIL";



// Get ElectionStatistics
export const GET_ELECTORS_BY_ALL = "GET_ELECTORS_BY_ALL";
export const GET_ELECTORS_BY_CATEGORY = "GET_ELECTORS_BY_CATEGORY";


// electorsBySearch
export const GET_ELECTORS_BY_SEARCH = "GET_ELECTORS_BY_SEARCH";
export const GET_ELECTOR_RELATED_ELECTORS = "GET_ELECTOR_RELATED_ELECTORS";


>>>>>>> sanad
