// ElectionStatistic Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Add Election
export const GET_ELECTORS = "GET_ELECTORS";
export const GET_ELECTORS_BY_CATEGORY = "GET_ELECTORS_BY_CATEGORY";
export const ADD_ELECTOR = "ADD_ELECTOR";
export const ADD_ELECTOR_SUCCESS = "ADD_ELECTOR_SUCCESS";
export const ADD_ELECTOR_FAIL = "ADD_ELECTOR_FAIL";



// Get ElectionStatistics
export const GET_ELECTOR_STATISTICS = "GET_ELECTOR_STATISTICS";
export const GET_ELECTORS_BY_FAMILY = "GET_ELECTORS_BY_FAMILY";

export const GET_ELECTOR_FAMILY_DIVISIONS = "GET_ELECTOR_FAMILY_DIVISIONS";