# Generated by Django 4.2.2 on 2023-08-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_rename_civil_id_user_civil_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="description"
            ),
        ),
    ]
