// ElectionData Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Get ElectionDatas
export const GET_ELECTION_DATA = "GET_ELECTION_DATA";

// Add ElectionData
export const ADD_ELECTION_DATA = "ADD_ELECTION_DATA";
export const ADD_ELECTION_DATA_SUCCESS = "ADD_ELECTION_DATA_SUCCESS";
export const ADD_ELECTION_DATA_FAIL = "ADD_ELECTION_DATA_FAIL";

// Edit ElectionData
export const UPDATE_ELECTION_DATA = "UPDATE_ELECTION_DATA";
export const UPDATE_ELECTION_DATA_SUCCESS = "UPDATE_ELECTION_DATA_SUCCESS";
export const UPDATE_ELECTION_DATA_FAIL = "UPDATE_ELECTION_DATA_FAIL";

// Delete ElectionData
export const DELETE_ELECTION_DATA = "DELETE_ELECTION_DATA";
export const DELETE_ELECTION_DATA_SUCCESS = "DELETE_ELECTION_DATA_SUCCESS";
export const DELETE_ELECTION_DATA_FAIL = "DELETE_ELECTION_DATA_FAIL";

// ElectionData Details
export const GET_ELECTION_DATA_DETAILS = "GET_ELECTION_DATA_DETAILS";

