# Generated by Django 5.0.4 on 2024-05-12 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0003_candidate_denomination_candidate_family_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'منشور'), (2, 'خاص'), (3, 'في أنتظار الموافقة'), (4, 'يفتقد للبيانات'), (5, 'جاري العمل عليه'), (6, 'جديد'), (9, 'محذوف')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(3, 'عالي'), (2, 'متوسط'), (1, 'منخفض')], null=True)),
                ('moderators', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('election_method', models.CharField(blank=True, choices=[('candidateOnly', 'Candidate Only System'), ('partyOnly', 'Party Only System'), ('partyCandidateOnly', 'Party Candidate Only System'), ('partyCandidateCombined', 'Combined Party Candidate System'), ('proportionalRepresentationSystem', 'Proportional Representation System'), ('mixedVoteralSystem', 'Mixed Voteral System')], max_length=50, null=True, verbose_name='Election Type')),
                ('election_result', models.TextField(blank=True, max_length=150, null=True, verbose_name='Election Result Type')),
                ('elect_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('elect_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('first_winner_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('last_winner_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('voters', models.PositiveIntegerField(default=0)),
                ('voters_males', models.PositiveIntegerField(default=0)),
                ('voters_females', models.PositiveIntegerField(default=0)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('attendees_males', models.PositiveIntegerField(default=0)),
                ('attendees_females', models.PositiveIntegerField(default=0)),
                ('has_schema', models.BooleanField(default=False, verbose_name='Has Specific Database')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'db_table': 'election',
                'permissions': [('canViewElection', 'Can View Election'), ('canAddElection', 'Can Add Election'), ('canChangeElection', 'Can Change Election'), ('canDeleteElection', 'Can Delete Election')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=25, null=True)),
                ('votes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_candidates', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_elections', to='elections.election')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election Candidate',
                'verbose_name_plural': 'Election Candidates',
                'db_table': 'election_candidate',
                'permissions': [('canViewElectionCandidate', 'Can View Election Candidate'), ('canAddElectionCandidate', 'Can Add Election Candidate'), ('canChangeElectionCandidate', 'Can Change Election Candidate'), ('canDeleteElectionCandidate', 'Can Delete Election Candidate')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='elections/')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.electioncategory')),
            ],
            options={
                'verbose_name': 'Election Category',
                'verbose_name_plural': 'Election  Category',
                'db_table': 'election_category',
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='election',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_elections', to='elections.electioncategory'),
        ),
        migrations.AddField(
            model_name='election',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_elections', to='elections.electioncategory'),
        ),
        migrations.CreateModel(
            name='ElectionParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_elections', to='elections.election')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_parties', to='candidates.party')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election Party',
                'verbose_name_plural': 'Election Parties',
                'db_table': 'election_party',
                'permissions': [],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionPartyCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_party_candidates', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_candidate_elections', to='elections.electionparty')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election Party Candidate',
                'verbose_name_plural': 'Election Parties Candidates',
                'db_table': 'election_party_candidate',
                'permissions': [],
                'default_permissions': [],
            },
        ),
    ]
