<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-11-24 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.0.4 on 2024-05-27 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> sanad


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '__first__'),
=======
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> sanad
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'منشور'), (2, 'خاص'), (3, 'في أنتظار الموافقة'), (4, 'يفتقد للبيانات'), (5, 'جاري العمل عليه'), (6, 'جديد'), (9, 'محذوف')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(3, 'عالي'), (2, 'متوسط'), (1, 'منخفض')], null=True)),
                ('moderators', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('elect_type', models.IntegerField(blank=True, choices=[(1, 'قوائم'), (2, 'مرشحين'), (3, 'قوائم ومرشحين')], null=True)),
                ('elect_result', models.IntegerField(blank=True, choices=[(1, 'نتائج نهائية'), (2, 'نتائج تفصيلية'), (3, 'نتائج الفرز')], null=True)),
                ('elect_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('elect_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('first_winner_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('last_winner_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('electors', models.PositiveIntegerField(blank=True, null=True)),
                ('electors_males', models.PositiveIntegerField(blank=True, null=True)),
                ('electors_females', models.PositiveIntegerField(blank=True, null=True)),
                ('attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('attendees_males', models.PositiveIntegerField(blank=True, null=True)),
                ('attendees_females', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Election',
=======
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'منشور'), (2, 'خاص'), (3, 'في أنتظار الموافقة'), (4, 'يفتقد للبيانات'), (5, 'جاري العمل عليه'), (6, 'جديد'), (7, 'تجريبي'), (9, 'محذوف')], null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'عالي')], null=True)),
                ('moderators', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('election_method', models.CharField(blank=True, choices=[('candidateOnly', 'Candidate Only System'), ('partyPartyOriented', 'Party Only System'), ('partyCandidateOriented', 'Party Candidate Only System'), ('partyCandidateCombined', 'Combined Party Candidate System'), ('proportionalRepresentationSystem', 'Proportional Representation System'), ('mixedVoteralSystem', 'Mixed Voteral System')], max_length=50, null=True, verbose_name='Election Type')),
                ('is_detailed_results', models.BooleanField(default=False, verbose_name='Is result in details (with committees)')),
                ('is_sorting_results', models.BooleanField(default=False, verbose_name='Is Sorting Results?')),
                ('elect_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('elect_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('elector_count', models.PositiveIntegerField(default=0)),
                ('elector_male_count', models.PositiveIntegerField(default=0)),
                ('elector_female_count', models.PositiveIntegerField(default=0)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('attendee_male_count', models.PositiveIntegerField(default=0)),
                ('attendee_female_count', models.PositiveIntegerField(default=0)),
                ('has_schema', models.BooleanField(default=False, verbose_name='Has Specific Database')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
>>>>>>> sanad
                'db_table': 'election',
                'permissions': [('canViewElection', 'Can View Election'), ('canAddElection', 'Can Add Election'), ('canChangeElection', 'Can Change Election'), ('canDeleteElection', 'Can Delete Election')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_candidates', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
=======
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=25, null=True)),
                ('votes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_candidates', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
>>>>>>> sanad
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_elections', to='elections.election')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election Candidate',
<<<<<<< HEAD
                'verbose_name_plural': 'Election Candidate',
=======
                'verbose_name_plural': 'Election Candidates',
>>>>>>> sanad
                'db_table': 'election_candidate',
                'permissions': [('canViewElectionCandidate', 'Can View Election Candidate'), ('canAddElectionCandidate', 'Can Add Election Candidate'), ('canChangeElectionCandidate', 'Can Change Election Candidate'), ('canDeleteElectionCandidate', 'Can Delete Election Candidate')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='ElectionCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'رجال'), (2, 'نساء')], null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_elections', to='elections.election')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election Committe',
                'verbose_name_plural': 'Election Committes',
                'db_table': 'election_committee',
                'permissions': [('canViewElectionCommitte', 'Can View Election Committe'), ('canAddElectionCommitte', 'Can Add Election Committe'), ('canChangeElectionCommitte', 'Can Change Election Committe'), ('canDeleteElectionCommitte', 'Can Delete Election Committe')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionCommitteeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_result_candidates', to='elections.electioncandidate')),
                ('election_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_result_elections', to='elections.electioncommittee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Committe Result',
                'verbose_name_plural': 'Committe Results',
                'db_table': 'election_committee_result',
                'permissions': [('canViewCommitteeResult', 'Can View Committee Result'), ('canAddCommitteeResult', 'Can Add Committee Result'), ('canChangeCommitteeResult', 'Can Change Committee Result'), ('canDeleteCommitteeResult', 'Can Delete Committee Result')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> sanad
            name='ElectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='elections/')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.electioncategory')),
            ],
            options={
                'verbose_name': 'Election Category',
                'verbose_name_plural': 'Election  Category',
                'db_table': 'election_category',
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='election',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_elections', to='elections.electioncategory'),
        ),
        migrations.AddField(
            model_name='election',
<<<<<<< HEAD
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='election',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='election',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_elections', to='elections.electioncategory'),
        ),
        migrations.AddField(
            model_name='election',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
=======
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_elections', to='elections.electioncategory'),
        ),
        migrations.CreateModel(
            name='ElectionParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_elections', to='elections.election')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_parties', to='candidates.party')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election Party',
                'verbose_name_plural': 'Election Parties',
                'db_table': 'election_party',
                'permissions': [],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ElectionPartyCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_party_candidates', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('election_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_candidate_elections', to='elections.electionparty')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Election Party Candidate',
                'verbose_name_plural': 'Election Parties Candidates',
                'db_table': 'election_party_candidate',
                'permissions': [],
                'default_permissions': [],
            },
>>>>>>> sanad
        ),
    ]
