# Generated by Django 4.2.2 on 2024-06-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionpartycandidate',
            name='candidate',
        ),
        migrations.AddField(
            model_name='electionpartycandidate',
            name='election_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_candidate_elections', to='elections.electioncandidate'),
        ),
        migrations.AlterField(
            model_name='electionpartycandidate',
            name='election_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_party_elections', to='elections.electionparty'),
        ),
    ]
