# Generated by Django 4.2.2 on 2024-05-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='voters',
            new_name='elections',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='voters_females',
            new_name='elections_females',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='voters_males',
            new_name='elections_males',
        ),
    ]
