# Generated by Django 5.0.4 on 2024-06-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_electionpartycandidate_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionparty',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='electionpartycandidate',
            old_name='notes',
            new_name='note',
        ),
    ]
