# Generated by Django 5.0.4 on 2024-06-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_rename_notes_electionparty_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_elector_address',
            field=models.BooleanField(default=False, verbose_name='Is elector address avaiable?'),
        ),
        migrations.AddField(
            model_name='election',
            name='is_elector_committee',
            field=models.BooleanField(default=False, verbose_name='Is elector committee avaiable?'),
        ),
    ]
