# Generated by Django 4.2.2 on 2024-05-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_rename_voters_election_elections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='attendees',
            new_name='attendee_count',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='attendees_females',
            new_name='attendees_female_count',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='attendees_males',
            new_name='attendees_male_count',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='elections',
            new_name='elector_count',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='elections_females',
            new_name='elector_female_count',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='elections_males',
            new_name='elector_male_count',
        ),
    ]
