# Generated by Django 4.2.2 on 2023-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0004_alter_election_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
