# Generated by Django 5.0.4 on 2024-05-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_rename_attendees_election_attendee_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electioncandidate',
            old_name='notes',
            new_name='note',
        ),
    ]
