# Generated by Django 5.0.4 on 2024-05-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_rename_notes_electioncandidate_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='attendees_female_count',
            new_name='attendee_female_count',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='attendees_male_count',
            new_name='attendee_male_count',
        ),
    ]
