# Generated by Django 4.2.2 on 2024-06-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_alter_election_is_detailed_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionpartycandidate',
            name='notes',
        ),
    ]
