# Generated by Django 5.0.4 on 2024-05-15 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_rename_attendees_female_count_election_attendee_female_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='electioncandidate',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='electionparty',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='electionpartycandidate',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='election',
            name='is_sorting',
            field=models.BooleanField(default=False, verbose_name='Is Sorting Results?'),
        ),
        migrations.AlterField(
            model_name='election',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
    ]
