# Generated by Django 5.0.4 on 2024-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_rename_is_detailed_result_election_is_detailed_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionpartycandidate',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
