# Generated by Django 5.0.4 on 2024-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_electionpartycandidate_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_method',
            field=models.CharField(blank=True, choices=[('candidateOnly', 'Candidate Only System'), ('partyPartyOriented', 'Party Only System'), ('partyCandidateOriented', 'Party Candidate Only System'), ('partyCandidateCombined', 'Combined Party Candidate System'), ('proportionalRepresentationSystem', 'Proportional Representation System'), ('mixedVoteralSystem', 'Mixed Voteral System')], max_length=50, null=True, verbose_name='Election Type'),
        ),
    ]
