# Generated by Django 4.2.2 on 2024-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_remove_electionpartycandidatecommitteeresult_election_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='electors',
            new_name='voters',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='electors_females',
            new_name='voters_females',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='electors_males',
            new_name='voters_males',
        ),
        migrations.AlterField(
            model_name='election',
            name='election_method',
            field=models.CharField(blank=True, choices=[('candidateOnly', 'Candidate Only System'), ('partyOnly', 'Party Only System'), ('partyCandidateOnly', 'Party Candidate Only System'), ('partyCandidateCombined', 'Combined Party Candidate System'), ('proportionalRepresentationSystem', 'Proportional Representation System'), ('mixedVoteralSystem', 'Mixed Voteral System')], max_length=50, null=True, verbose_name='Election Type'),
        ),
    ]
