# Generated by Django 5.0.4 on 2024-04-12 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0017_alter_election_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncommitteegroup',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_group_elections', to='elections.election'),
        ),
    ]
