# Generated by Django 5.0.4 on 2024-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0019_electioncommittee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncommitteegroup',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'رجال'), (2, 'نساء')], null=True),
        ),
    ]
