# Generated by Django 4.2.2 on 2024-04-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_alter_electioncommitteegroup_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncommittee',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electioncommittee',
            name='committee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='elections.electioncommitteegroup'),
        ),
    ]
