# Generated by Django 5.0.4 on 2024-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0022_electioncandidate_position_electioncandidate_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncandidate',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electioncandidate',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
