# Generated by Django 5.0.4 on 2024-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0023_alter_electioncandidate_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncandidate',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
