# Generated by Django 5.0.4 on 2024-04-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0024_alter_electioncandidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='has_data_base',
            field=models.BooleanField(default=False, verbose_name='Has Specific Database'),
        ),
        migrations.CreateModel(
            name='ElectionDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_data_base', models.BooleanField(default=False, verbose_name='Has Specific Database')),
                ('database_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Database Name')),
                ('database_url', models.URLField(blank=True, null=True, verbose_name='Database URL')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_base', to='elections.election', verbose_name='Election')),
            ],
            options={
                'verbose_name': 'Election Database',
                'verbose_name_plural': 'Election Databases',
            },
        ),
    ]
