# Generated by Django 5.0.4 on 2024-04-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_election_has_data_base_electiondatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='has_data_base',
            new_name='has_database',
        ),
        migrations.DeleteModel(
            name='ElectionDataBase',
        ),
    ]
