# Generated by Django 5.0.4 on 2024-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0026_rename_has_data_base_election_has_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='election',
            name='attendees_females',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='election',
            name='attendees_males',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='election',
            name='voters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='election',
            name='voters_females',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='election',
            name='voters_males',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
