# Generated by Django 5.0.4 on 2024-04-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0027_alter_election_attendees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='has_database',
            new_name='has_data_schema',
        ),
    ]
