# Generated by Django 5.0.4 on 2024-04-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0028_rename_has_database_election_has_data_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='has_data_schema',
            new_name='has_schema',
        ),
    ]
