// Candidate Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";


// Get Candidates
export const GET_CANDIDATES = "GET_CANDIDATES";
export const GET_CANDIDATE_COUNT = "GET_CANDIDATE_COUNT";

// Add Candidate
export const ADD_NEW_CANDIDATE = "ADD_NEW_CANDIDATE";
export const ADD_NEW_CANDIDATE_SUCCESS = "ADD_NEW_CANDIDATE_SUCCESS";
export const ADD_NEW_CANDIDATE_FAIL = "ADD_NEW_CANDIDATE_FAIL";

// Edit Candidate
export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";
export const UPDATE_CANDIDATE_SUCCESS = "UPDATE_CANDIDATE_SUCCESS";
export const UPDATE_CANDIDATE_FAIL = "UPDATE_CANDIDATE_FAIL";

// Delete Candidate
export const DELETE_CANDIDATE = "DELETE_CANDIDATE";
export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAIL = "DELETE_CANDIDATE_FAIL";

// Candidate Details
export const GET_CANDIDATE_DETAILS = "GET_CANDIDATE_DETAILS";



// Candidate Candidates
export const GET_CANDIDATE_CANDIDATES = "GET_CANDIDATE_CANDIDATES";
export const GET_CANDIDATE_CANDIDATES_SUCCESS = "GET_CANDIDATE_CANDIDATES_SUCCESS";
export const GET_CANDIDATE_CANDIDATES_FAIL = "GET_CANDIDATE_CANDIDATES_FAIL";

// Add Candidate Candidate
export const ADD_NEW_CANDIDATE_CANDIDATE = "ADD_NEW_CANDIDATE_CANDIDATE";
export const ADD_NEW_CANDIDATE_CANDIDATE_SUCCESS = "ADD_NEW_CANDIDATE_CANDIDATE_SUCCESS";
export const ADD_NEW_CANDIDATE_CANDIDATE_FAIL = "ADD_NEW_CANDIDATE_CANDIDATE_FAIL";

// Edit Candidate Candidate
export const UPDATE_CANDIDATE_CANDIDATE = "UPDATE_CANDIDATE_CANDIDATE";
export const UPDATE_CANDIDATE_CANDIDATE_SUCCESS = "UPDATE_CANDIDATE_CANDIDATE_SUCCESS";
export const UPDATE_CANDIDATE_CANDIDATE_FAIL = "UPDATE_CANDIDATE_CANDIDATE_FAIL";

// Delete Candidate Candidate
export const DELETE_CANDIDATE_CANDIDATE = "DELETE_CANDIDATE_CANDIDATE";
export const DELETE_CANDIDATE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_CANDIDATE_FAIL = "DELETE_CANDIDATE_CANDIDATE_FAIL";

// Candidate Candidate Details
// export const GET_CANDIDATE_CANDIDATE_DETAILS = "GET_CANDIDATE_CANDIDATE_DETAILS";
// export const GET_CANDIDATE_CANDIDATE_COUNT = "GET_CANDIDATE_CANDIDATE_COUNT";


// Candidate Campaigns
export const GET_CANDIDATE_CAMPAIGNS = "GET_CANDIDATE_CAMPAIGNS";
export const GET_CANDIDATE_CAMPAIGNS_SUCCESS = "GET_CANDIDATE_CAMPAIGNS_SUCCESS";
export const GET_CANDIDATE_CAMPAIGNS_FAIL = "GET_CANDIDATE_CAMPAIGNS_FAIL";

// Add Candidate Campaign
export const ADD_NEW_CANDIDATE_CAMPAIGN = "ADD_NEW_CANDIDATE_CAMPAIGN";
export const ADD_NEW_CANDIDATE_CAMPAIGN_SUCCESS = "ADD_NEW_CANDIDATE_CAMPAIGN_SUCCESS";
export const ADD_NEW_CANDIDATE_CAMPAIGN_FAIL = "ADD_NEW_CANDIDATE_CAMPAIGN_FAIL";

// Edit Candidate Campaign
export const UPDATE_CANDIDATE_CAMPAIGN = "UPDATE_CANDIDATE_CAMPAIGN";
export const UPDATE_CANDIDATE_CAMPAIGN_SUCCESS = "UPDATE_CANDIDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CANDIDATE_CAMPAIGN_FAIL = "UPDATE_CANDIDATE_CAMPAIGN_FAIL";

// Delete Candidate Campaign
export const DELETE_CANDIDATE_CAMPAIGN = "DELETE_CANDIDATE_CAMPAIGN";
export const DELETE_CANDIDATE_CAMPAIGN_SUCCESS = "DELETE_CANDIDATE_CAMPAIGN_SUCCESS";
export const DELETE_CANDIDATE_CAMPAIGN_FAIL = "DELETE_CANDIDATE_CAMPAIGN_FAIL";

// Candidate Campaign Details
export const GET_CANDIDATE_CAMPAIGN_DETAILS = "GET_CANDIDATE_CAMPAIGN_DETAILS";
export const GET_CANDIDATE_CAMPAIGN_COUNT = "GET_CANDIDATE_CAMPAIGN_COUNT";
