// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_ALL_CAMPAIGN_GUARANTEES = "GET_ALL_CAMPAIGN_GUARANTEES";

// Add CampaignGuarantee
<<<<<<< HEAD
export const ADD_NEW_CAMPAIGN_GUARANTEE = "ADD_NEW_CAMPAIGN_GUARANTEE";
export const ADD_NEW_CAMPAIGN_GUARANTEEN_SUCCESS = "ADD_NEW_CAMPAIGN_GUARANTEEN_SUCCESS";
export const ADD_NEW_CAMPAIGN_GUARANTEEN_FAIL = "ADD_NEW_CAMPAIGN_GUARANTEEN_FAIL";
=======
export const ADD_CAMPAIGN_GUARANTEE = "ADD_CAMPAIGN_GUARANTEE";
export const ADD_CAMPAIGN_GUARANTEEN_SUCCESS = "ADD_CAMPAIGN_GUARANTEEN_SUCCESS";
export const ADD_CAMPAIGN_GUARANTEEN_FAIL = "ADD_CAMPAIGN_GUARANTEEN_FAIL";
>>>>>>> sanad

// Edit CampaignGuarantee
export const UPDATE_CAMPAIGN_GUARANTEE = "UPDATE_CAMPAIGN_GUARANTEE";
export const UPDATE_CAMPAIGN_GUARANTEE_SUCCESS = "UPDATE_CAMPAIGN_GUARANTEE_SUCCESS";
export const UPDATE_CAMPAIGN_GUARANTEE_FAIL = "UPDATE_CAMPAIGN_GUARANTEE_FAIL";

// Delete CampaignGuarantee
export const DELETE_CAMPAIGN_GUARANTEE = "DELETE_CAMPAIGN_GUARANTEE";
export const DELETE_CAMPAIGN_GUARANTEE_SUCCESS = "DELETE_CAMPAIGN_GUARANTEE_SUCCESS";
export const DELETE_CAMPAIGN_GUARANTEE_FAIL = "DELETE_CAMPAIGN_GUARANTEE_FAIL";
