// User Success / Error
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

// Get Users
export const GET_USERS = "GET_USERS";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_MODERATOR_USERS = "GET_MODERATOR_USERS";

// Add User
export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";
export const ADD_NEW_USER_FAIL = "ADD_NEW_USER_FAIL";

// Edit User
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

// Delete User
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// User Details



// User Candidates
export const GET_USER_CANDIDATES = "GET_USER_CANDIDATES";
export const GET_USER_CANDIDATES_SUCCESS = "GET_USER_CANDIDATES_SUCCESS";
export const GET_USER_CANDIDATES_FAIL = "GET_USER_CANDIDATES_FAIL";

// Add User Candidate
export const ADD_NEW_USER_CANDIDATE = "ADD_NEW_USER_CANDIDATE";
export const ADD_NEW_USER_CANDIDATE_SUCCESS = "ADD_NEW_USER_CANDIDATE_SUCCESS";
export const ADD_NEW_USER_CANDIDATE_FAIL = "ADD_NEW_USER_CANDIDATE_FAIL";

// Edit User Candidate
export const UPDATE_USER_CANDIDATE = "UPDATE_USER_CANDIDATE";
export const UPDATE_USER_CANDIDATE_SUCCESS = "UPDATE_USER_CANDIDATE_SUCCESS";
export const UPDATE_USER_CANDIDATE_FAIL = "UPDATE_USER_CANDIDATE_FAIL";

// Delete User Candidate
export const DELETE_USER_CANDIDATE = "DELETE_USER_CANDIDATE";
export const DELETE_USER_CANDIDATE_SUCCESS = "DELETE_USER_CANDIDATE_SUCCESS";
export const DELETE_USER_CANDIDATE_FAIL = "DELETE_USER_CANDIDATE_FAIL";

// User Candidate Details
// export const GET_USER_CANDIDATE_DETAILS = "GET_USER_CANDIDATE_DETAILS";
// export const GET_USER_CANDIDATE_COUNT = "GET_USER_CANDIDATE_COUNT";


// User Campaigns
export const GET_USER_CAMPAIGNS = "GET_USER_CAMPAIGNS";
export const GET_USER_CAMPAIGNS_SUCCESS = "GET_USER_CAMPAIGNS_SUCCESS";
export const GET_USER_CAMPAIGNS_FAIL = "GET_USER_CAMPAIGNS_FAIL";

// Add User Campaign
export const ADD_NEW_USER_CAMPAIGN = "ADD_NEW_USER_CAMPAIGN";
export const ADD_NEW_USER_CAMPAIGN_SUCCESS = "ADD_NEW_USER_CAMPAIGN_SUCCESS";
export const ADD_NEW_USER_CAMPAIGN_FAIL = "ADD_NEW_USER_CAMPAIGN_FAIL";

// Edit User Campaign
export const UPDATE_USER_CAMPAIGN = "UPDATE_USER_CAMPAIGN";
export const UPDATE_USER_CAMPAIGN_SUCCESS = "UPDATE_USER_CAMPAIGN_SUCCESS";
export const UPDATE_USER_CAMPAIGN_FAIL = "UPDATE_USER_CAMPAIGN_FAIL";

// Delete User Campaign
export const DELETE_USER_CAMPAIGN = "DELETE_USER_CAMPAIGN";
export const DELETE_USER_CAMPAIGN_SUCCESS = "DELETE_USER_CAMPAIGN_SUCCESS";
export const DELETE_USER_CAMPAIGN_FAIL = "DELETE_USER_CAMPAIGN_FAIL";

// User Campaign Details
// export const GET_USER_CAMPAIGN_DETAILS = "GET_USER_CAMPAIGN_DETAILS";
// export const GET_USER_CAMPAIGN_COUNT = "GET_USER_CAMPAIGN_COUNT";