# Generated by Django 5.0.4 on 2024-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('circle', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('voter_count', models.IntegerField(blank=True, null=True)),
                ('committee_count', models.IntegerField(blank=True, null=True)),
                ('total_voters', models.IntegerField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('second_name', models.TextField(blank=True, null=True)),
                ('third_name', models.TextField(blank=True, null=True)),
                ('fourth_name', models.TextField(blank=True, null=True)),
                ('fifth_name', models.TextField(blank=True, null=True)),
                ('sixth_name', models.TextField(blank=True, null=True)),
                ('seventh_name', models.TextField(blank=True, null=True)),
                ('eighth_name', models.TextField(blank=True, null=True)),
                ('ninth_name', models.TextField(blank=True, null=True)),
                ('tenth_name', models.TextField(blank=True, null=True)),
                ('eleventh_name', models.TextField(blank=True, null=True)),
                ('twelveth_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('tribe', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('sect', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=1, null=True)),
                ('circle', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('lane', models.TextField(blank=True, null=True)),
                ('house', models.TextField(blank=True, null=True)),
                ('column6', models.TextField(blank=True, null=True)),
                ('national_table_name', models.TextField(blank=True, null=True)),
                ('status_code', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('committee', models.TextField(blank=True, null=True)),
                ('letter', models.TextField(blank=True, null=True)),
                ('code_char', models.TextField(blank=True, null=True)),
                ('vote', models.TextField(blank=True, null=True)),
                ('groups', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.TextField(blank=True, null=True)),
                ('letters', models.TextField(blank=True, null=True)),
                ('main', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
