# Generated by Django 4.2.3 on 2023-07-31 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_address_user_background_image_user_civil_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="background_image",
            new_name="background",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="profile_image",
            new_name="image",
        ),
    ]
