# Generated by Django 4.2.3 on 2023-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_rename_background_image_user_background_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
