# Generated by Django 4.2.2 on 2023-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="civil_id",
            new_name="civil",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="start_date",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="mobile",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="education_level",
            new_name="twitter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="about",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_candidate",
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
