# Generated by Django 5.0.4 on 2024-06-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortingcampaign',
            options={'managed': False, 'verbose_name': 'Sorting Campaign', 'verbose_name_plural': 'فرز الحملة'},
        ),
        migrations.AlterModelOptions(
            name='sortingelection',
            options={'managed': False, 'verbose_name': 'Sorting Election', 'verbose_name_plural': 'فرز الانتخابات'},
        ),
        migrations.AlterModelTable(
            name='sortingcampaign',
            table='sorting_campaign',
        ),
        migrations.AlterModelTable(
            name='sortingelection',
            table='sorting_election',
        ),
    ]
