# Generated by Django 5.0.4 on 2024-06-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeeresultcandidate',
            options={'managed': False, 'verbose_name': 'Committee Result Candidate', 'verbose_name_plural': 'نتائج اللجان'},
        ),
    ]
