# Generated by Django 4.2.2 on 2024-06-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseCommitteeResult',
        ),
    ]
