# Generated by Django 5.0.4 on 2024-06-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_committeemember_committeesitemember'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='committeemember',
            table='committee_site_member',
        ),
    ]
