# Generated by Django 5.0.4 on 2024-06-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_membercommittee_membercommitteesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Election Attendee',
                'verbose_name_plural': 'Election Attendees',
                'db_table': 'election_attendee',
                'permissions': [('canViewElectionAttendee', 'Can View Election Attendee'), ('canAddElectionAttendee', 'Can Add Election Attendee'), ('canChangeElectionAttendee', 'Can Change Election Attendee'), ('canDeleteElectionAttendee', 'Can Delete Election Attendee')],
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.AlterModelOptions(
            name='membercommittee',
            options={'managed': False, 'verbose_name': 'Member Committee', 'verbose_name_plural': 'Member Committees'},
        ),
        migrations.AlterModelOptions(
            name='membercommitteesite',
            options={'managed': False, 'verbose_name': 'Member Committee Site', 'verbose_name_plural': 'Member Committee Sites'},
        ),
        migrations.AlterModelTable(
            name='membercommittee',
            table='member_committee',
        ),
        migrations.AlterModelTable(
            name='membercommitteesite',
            table='member_committee_site',
        ),
    ]
