# Generated by Django 4.2.2 on 2024-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_electionattendee_alter_membercommittee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'الحضور',
                'verbose_name_plural': 'الحضور',
                'db_table': 'campaign_attendee',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ElectionAttendee',
        ),
        migrations.AlterModelOptions(
            name='campaignguarantee',
            options={'verbose_name': 'المضامين', 'verbose_name_plural': 'المضامين'},
        ),
        migrations.RemoveField(
            model_name='campaignguarantee',
            name='member2',
        ),
    ]
