# Generated by Django 4.2.2 on 2024-05-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True, unique=True)),
                ('value', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Setting',
                'db_table': 'setting',
                'permissions': [('canViewSetting', 'Can View Setting'), ('canAddSetting', 'Can Add Setting'), ('canChangeSetting', 'Can Change Setting'), ('canDeleteSetting', 'Can Delete Setting')],
                'default_permissions': [],
            },
        ),
    ]
