# Generated by Django 5.0.4 on 2024-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True, unique=True)),
                ('value', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
                'db_table': 'config',
                'permissions': [('canViewConfig', 'Can View Config'), ('canAddConfig', 'Can Add Config'), ('canChangeConfig', 'Can Change Config'), ('canDeleteConfig', 'Can Delete Config')],
                'default_permissions': [],
            },
        ),
    ]
