# Generated by Django 5.0.4 on 2024-04-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='Setting',
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'default_permissions': [], 'permissions': [('canViewSetting', 'Can View Setting'), ('canAddSetting', 'Can Add Setting'), ('canChangeSetting', 'Can Change Setting'), ('canDeleteSetting', 'Can Delete Setting')], 'verbose_name': 'Setting', 'verbose_name_plural': 'Setting'},
        ),
        migrations.AlterModelTable(
            name='setting',
            table='setting',
        ),
    ]
