# Generated by Django 5.0.4 on 2024-05-15 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user who is_deleted this object.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_is_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
    ]
