# Generated by Django 4.2.2 on 2024-03-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_user_created_at_user_created_by_user_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
