# Generated by Django 4.2.2 on 2024-03-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0004_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_expiry",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
