# Generated by Django 5.0.4 on 2024-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_user_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Undefined'), (1, 'رجال'), (2, 'نساء')], default=1, null=True),
        ),
    ]
