# Generated by Django 4.2.2 on 2024-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0005_user_token_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
