# Generated by Django 5.0.4 on 2024-04-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
