# Generated by Django 5.0.4 on 2024-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'default_permissions': [], 'managed': False, 'verbose_name': 'اللجنة', 'verbose_name_plural': 'اللجان'},
        ),
        migrations.AlterModelOptions(
            name='committeesite',
            options={'default_permissions': [], 'managed': False, 'verbose_name': 'موقع اللجنة', 'verbose_name_plural': 'مواقع اللجان'},
        ),
    ]
