# Generated by Django 5.0.4 on 2024-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_alter_committee_options_alter_committeesite_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeCandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Committee Candidate Result',
                'verbose_name_plural': 'Committee Candidate Results',
                'db_table': 'committee_candidate_result',
                'managed': False,
            },
        ),
    ]
