# Generated by Django 5.0.4 on 2024-04-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_delete_committee'),
        ('committees', '0002_committee_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committee',
            new_name='CommitteeGroups',
        ),
        migrations.AlterModelOptions(
            name='committeegroups',
            options={'default_permissions': [], 'verbose_name': 'Committee Group', 'verbose_name_plural': 'Committee Groups'},
        ),
        migrations.RenameField(
            model_name='committeegroups',
            old_name='school',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='committeegroups',
            table='committee_grouo',
        ),
    ]
