# Generated by Django 5.0.4 on 2024-04-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_delete_committee'),
        ('committees', '0003_rename_committee_committeegroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('committee_no', models.IntegerField()),
                ('circle', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('voter_count', models.IntegerField()),
                ('committee_count', models.IntegerField()),
                ('total_voters', models.IntegerField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_areas', to='areas.area')),
            ],
            options={
                'verbose_name': 'Committee Group',
                'verbose_name_plural': 'Committee Groups',
                'db_table': 'committee_group',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.IntegerField()),
                ('letters', models.CharField(max_length=255)),
                ('areas', models.CharField(max_length=255)),
                ('committee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_committee_groups', to='committees.committeegroup')),
            ],
            options={
                'verbose_name': 'Committee Group',
                'verbose_name_plural': 'Committee Groups',
                'db_table': 'committee',
                'default_permissions': [],
            },
        ),
        migrations.DeleteModel(
            name='CommitteeGroups',
        ),
    ]
