# Generated by Django 5.0.4 on 2024-05-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committeecandidateresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyCandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Party Candidate Committee Result',
                'verbose_name_plural': 'Party Candidate Committee Results',
                'db_table': 'party_candidate_committee_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Party Committee Result',
                'verbose_name_plural': 'Party Committee Results',
                'db_table': 'party_committee_result',
                'managed': False,
            },
        ),
    ]
