# Generated by Django 5.0.4 on 2024-05-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_partycandidateresult_partyresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'default_permissions': [], 'verbose_name': 'اللجنة', 'verbose_name_plural': 'اللجان'},
        ),
        migrations.AlterModelOptions(
            name='committeecandidateresult',
            options={'verbose_name': 'Committee Candidate Result', 'verbose_name_plural': 'Committee Candidate Results'},
        ),
        migrations.AlterModelOptions(
            name='committeesite',
            options={'default_permissions': [], 'verbose_name': 'موقع اللجنة', 'verbose_name_plural': 'مواقع اللجان'},
        ),
        migrations.AlterModelOptions(
            name='partycandidateresult',
            options={'verbose_name': 'Party Candidate Result', 'verbose_name_plural': 'Party Candidate Results'},
        ),
        migrations.AlterModelOptions(
            name='partyresult',
            options={'verbose_name': 'Party Result', 'verbose_name_plural': 'Party Results'},
        ),
    ]
