# Generated by Django 5.0.4 on 2024-04-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committeegroup_committee_delete_committeegroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeegroup',
            name='area',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='CommitteeGroup',
        ),
    ]
