# Generated by Django 5.0.4 on 2024-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_committeelocation_delete_committeesubset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('circle', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('voter_count', models.IntegerField(blank=True, null=True)),
                ('committee_count', models.IntegerField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('election', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Committee Location',
                'verbose_name_plural': 'Committee Locations',
                'db_table': 'committee_site',
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.DeleteModel(
            name='CommitteeLocation',
        ),
    ]
